services:
  postgres:
    image: postgres:17
    container_name: sga_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: er1121
      POSTGRES_DB: sga_db
    ports:
      - "5432:5432"
    volumes:
      - sga_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: sga_redis
    restart: unless-stopped
    ports:
      - "6379:6379"

volumes:
  sga_postgres_data: