services:
  postgres:
    image: postgres:17
    container_name: sga_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: er1121
      POSTGRES_DB: sga_db
    ports:
      - "5432:5432"
    volumes:
      - sga_postgres_data:/var/lib/postgresql/data
 
  redis:
    image: redis:7
    container_name: sga_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
 
  minio:
    image: minio/minio
    container_name: sga_minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - sga_minio_data:/data
    command: server /data --console-address ":9001"
 
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: sga_rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    ports:
      - "5672:5672"
      - "15672:15672"
 
volumes:
  sga_postgres_data:
  sga_minio_data: