ALTER TABLE docentes ADD COLUMN IF NOT EXISTS cedula VARCHAR(20);
 
ALTER TABLE docentes ALTER COLUMN cedula SET NOT NULL;
ALTER TABLE docentes ALTER COLUMN titulo SET NOT NULL;
ALTER TABLE docentes ALTER COLUMN especialidad SET NOT NULL;